name: Inline-Perl
version: 0.01
abstract: Inline module for another Perl interpreter
author: Autrijus Tang <autrijus@autrijus.org>
license: perl
distribution_type: module
build_requires:
  Test::More: 0
requires:
  Inline: 0.43
  Perl: 0.03
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
